services:
  xcloudlambda:
    image: xcloudlambda
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      CLOUD_PROVIDER: Docker Compose
networks:
  default:


